name: Mac Unit Testing and Deployment

on:
  push:
    branches: "*"
    tags: "*"
  pull_request:
    branches: "**"

jobs:
  macOS:
    runs-on: macos-latest
    name: Mac OS Unit Testing
    strategy:
      matrix:
        python-version: ['3.8']

    env:
      SHELLOPTS: 'errexit:pipefail'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Build wheels
        uses: joerick/cibuildwheel@v2.0.1
        env:
          CIBW_BEFORE_BUILD: pip install -r requirements_build.txt
          CIBW_BUILD: cp38-macosx_x86_64
          CIBW_BEFORE_TEST: pip install -r requirements_test.txt
          CIBW_TEST_COMMAND: pytest -v

      - name: Build wheels
        if: startsWith(github.event.ref, 'refs/tags')
        uses: joerick/cibuildwheel@v2.0.1
        env:
          CIBW_BEFORE_BUILD: pip install -r requirements_build.txt
          CIBW_SKIP: pp* cp38-macosx_x86_64
          CIBW_BEFORE_TEST: pip install -r requirements_test.txt
          CIBW_TEST_COMMAND: pytest -v

      - name: Show files
        run: ls -lh wheelhouse
        shell: bash

      - name: Upload wheels
        uses: actions/upload-artifact@v2
        with:
          path: wheelhouse/*.whl

      - name: Upload to PyPi
        if: startsWith(github.event.ref, 'refs/tags')
        run: |
          twine upload -u __token__ --skip-existing wheelhouse/*
        env:
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
